---
- name: Install Nginx and Hello World on Linux
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    # default for Debian/Ubuntu
    web_root: "/var/www/html"

  pre_tasks:
    - name: Switch web root for RedHat-family distros
      set_fact:
        web_root: "/usr/share/nginx/html"
      when: ansible_os_family == "RedHat"

  tasks:
    - name: Update apt repo cache (Ubuntu/Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Enable and start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Remove Ubuntu default nginx placeholder page
      file:
        path: /var/www/html/index.nginx-debian.html
        state: absent
      when: ansible_os_family == "Debian"

    - name: Deploy Hello World page
      copy:
        dest: "{{ web_root }}/index.html"
        content: |
          <html>
          <head><title>Terraform + Ansible + Linux + Nginx</title></head>
          <body style="font-family: Arial; text-align:center; margin-top:50px;">
            <h1>Hello World!</h1>
            <h3>Nginx is installed on Linux</h3>
          </body>
          </html>
        owner: root
        group: root
        mode: "0644"
